version: '3.2'

services:

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    hostname: mysql
    environment:
      MYSQL_DATABASE: hw2
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password

  webapp:
    build: .
    image: webapp
    ports:
      - 8000:8000
    depends_on:
      - "mysql"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080